### ISSUE TITLE
Build fail on nodejs 14.

### ISSUE THREAD

**Issue by cweijan** [unjs/unplugin#364]
### Environment

nodejs14

### Reproduction

Build using nodejs14.

### Describe the bug

The new code cannot be executed on nodejs14 because logical OR is used.

### Logs

```sh
error during build:
/home/runner/work/vscode-office/vscode-office/packages/zip-viewer/node_modules/unplugin/dist/index.js:1021
            loader.options ||= _options;
                           ^^^

SyntaxError: Unexpected token '||='
```

**Comment by cweijan** [comment]
I solved it by upgrading the node version of CI, but errors occurred due to unplugin when the code was not changed, which was frustrating.

If it is not compatible with the old version of nodejs, the unplugin version should be upgraded to 2.x

**Comment by purple-color** [comment]
更新node版本到16.20.0不再报语法错误

**Comment by FAOfao931013** [comment]
我更新到 16.20.2 构建成功了

**Comment by kanfashidoufu** [comment]
一样的问题 是因为使用了||=逻辑或语法 需要Node v15.0.0以上支持 但是不向下兼容不理解

**Comment by raind33** [comment]
我们也是node不能轻易切换，遇到这个问题了

**Comment by cweijan** [comment]
我才发现这个1.8.0版本是在不到24小时前发布的,  难怪这帖这么热闹, 我刚好拿起了我很久没维护的项目🤣.

**Comment by XinChou16** [comment]
报错了，node14, 不能随便升版本

**Comment by XinChou16** [comment]
这个属于破坏性变更了吧

**Comment by XinChou16** [comment]
@antfu Maybe we should release a new version v1.8.1, ASAP?

**Comment by sxzz** [comment]
In fact, since the first version of unplugin, the minimum supported version has been node v16. However, it seems that we did not specify this in the documentation. Also considering that currently there seem to be many users of unplugin still on node 14.

Therefore, we have decided to lower the minimum supported version to v14 and will note this in the documentation. We will drop support for v14 when releasing unplugin v2 in the future.
