### ISSUE TITLE
Feature: Next.js compatibility

### ISSUE THREAD

**Issue by hyf0** [unjs/unplugin#43]
In fact, after supporting webpack, there is a little work to do to let unplugin support nextjs.

Writing these glue codes is indeed tedious, So could we just make it in unplugin, I'm very happy to make PR for this.

---

By the way, unplugin is amazing. The DX of writing Webpack plugin is horrible, but with unplugin the pain is disappeared.

**Comment by Atinux** [comment]
Would be nice to have some thoughts from Next team (@leerob)

**Comment by ecstrema** [comment]
@hyf0 What exactly is needed to make a webpack plugin work with next? Aren't all webpack plugins nextjs compatible?

**Comment by antfu** [comment]
I think at this point, directly supporting meta-frameworks is out-of-scope of unplugin. We are focusing on build tools that have similar scopes.

For turbopack I think the problem is that it doesn't support a flexible enough plugin system that can fix the feature parity of unplugin. We will keep an eye on it but I think it might not happen very soon.
